apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://katedra2.jblew.pl:16443
  name: katedra2
contexts:
- context:
    cluster: katedra2
    user: katedra2_jblew
    namespace: clampfit-exporter
  name: katedra2
current-context: katedra2
kind: Config
preferences: {}
users:
- name: katedra2_jblew
  user:
    client-certificate: /Users/jedrzejlewandowski/.k8_cert/jblew.crt
    client-key: /Users/jedrzejlewandowski/.k8_cert/jblew.key