apiVersion: v1
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: https://katedra2.jblew.pl:16443
    name: katedra2
contexts:
  - context:
      cluster: katedra2
      namespace: clampfit-exporter-staging
      user: ns-default-user
    name: default-ctx
current-context: default-ctx
kind: Config
preferences: {}
users:
