apiVersion: v1
kind: Service
metadata:
  name: backend
  labels: { service: backend }
spec:
  selector: { service: backend }
  ports: [{ port: 80, targetPort: 80 }]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: { service: backend }
spec:
  replicas: 1
  selector: { matchLabels: { service: backend } }
  template:
    metadata: { labels: { service: backend } }
    spec:
      # imagePullSecrets: [{ name: dockerconfigjson-github-com }] # If the image was private on ghcr.io (consult 1myears/totus or 1myears/extensa-deploy)
      restartPolicy: Always
      containers:
        - name: backend
          image: ghcr.io/jblew/clampfit-exporter-backend:1.6.0
          ports: [{ containerPort: 80 }]
          env:
            - name: PORT
              value: "80"
            - name: BASE_URL
              value: "https://clamper.jblew.pl/api"
            - name: FRONTEND_REDIRECT_URL
              value: "https://clamper.jblew.pl/"
            - name: OIDC_ISSUER_BASEURL
              valueFrom:
                secretKeyRef:
                  name: oidc
                  key: issuer_baseurl
            - name: OIDC_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: oidc
                  key: auth_secret
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oidc
                  key: client_id
