apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule: "15 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: db-backup
              image: ghcr.io/jblew/postgres-backup-s3:1.0.2
              imagePullPolicy: IfNotPresent
              env:
                - name: "POSTGRES_HOST"
                  value: "db"
                - name: "POSTGRES_DATABASE"
                  value: "postgres"
                - name: "POSTGRES_USER"
                  value: "postgres"
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-credentials
                      key: password
                - name: "S3_REGION"
                  value: "eu-north-1"
                - name: "S3_BUCKET"
                  value: "katedra2-backups"
                - name: S3_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-bucket-credentials
                      key: accesskeyid
                - name: S3_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-bucket-credentials
                      key: secretaccesskey
          restartPolicy: OnFailure
