name: "apply k8"

on:
  push:
    branches: ["release"]
    tags:
      - "v*"

jobs:
  build:
    name: Deploy to katedra2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          submodules: false
      
      - name: "Envsubst variables in k8/*.yml"
        run: |
          export IMAGES_VERSION_BASED_ON_GIT_TAG="${GIT_REF:1}" # Strips the v prefix

          for file in k8/*.yml
          do
              echo "====${file}===="
              envsubst < "${file}" > "${file}.out" && mv "${file}.out" "${file}"
              cat  "${file}"
              echo "\n"
          done
        env:
          GIT_REF: "${{ github.ref_name }}"

      - name: "Prepare cert files"
        run: |
          echo "${K8_CLIENT_CERTIFICATE}" > "$HOME/k8_x509_cert.crt"
          echo "${K8_CLIENT_KEY}" > "$HOME/k8_x509_key.key"
        env:
          K8_CLIENT_CERTIFICATE: ${{ secrets.K8_CLIENT_CERTIFICATE }}
          K8_CLIENT_KEY: ${{ secrets.K8_CLIENT_KEY }}

      - name: Deploy to Kubernetes
        run: |
          kubectl \
            --server "${K8_SERVER}" --insecure-skip-tls-verify \
            --client-certificate "$HOME/k8_x509_cert.crt" \
            --client-key "$HOME/k8_x509_key.key" \
            apply \
            -f "k8" --namespace "${K8_NAMESPACE}"
        env:
          K8_SERVER: "https://katedra2.jblew.pl:16443"
          K8_NAMESPACE: clampfit-exporter
