name: "apply k8"

on:
  push:
    branches:
      - main
      - staging
    tags: ["*"]

jobs:
  build:
    name: Deploy to katedra2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0 # Fetch all history so that tags are available (for GIT_LATEST_TAG)

      - name: "Config for production"
        if: github.ref_name == 'main'
        env:
          K8_ENV_FILE: "k8/.env.production"
          KUBECONFIG_PRODUCTION: ${{ secrets.KUBECONFIG_PRODUCTION }}
        run: |
          mv "${K8_ENV_FILE}" k8/.env
          echo "${KUBECONFIG_PRODUCTION}" > .kubeconfig.yml

      - name: "Config for staging"
        if: github.ref_name == 'staging'
        env:
          K8_ENV_FILE: "k8/.env.staging"
          KUBECONFIG_PRODUCTION: ${{ secrets.KUBECONFIG_STAGING }}
        run: |
          mv "${K8_ENV_FILE}" k8/.env
          echo "${KUBECONFIG_PRODUCTION}" > /kubeconfig.yml

      - name: "Envsubst variables in k8/*.yml"
        run: |
          GIT_LATEST_TAG="$(git describe --abbrev=0 --tags)"
          export IMAGES_VERSION_BASED_ON_GIT_TAG="${GIT_LATEST_TAG:1}" # Strips the v prefix
          export $(cat k8/.env | sed 's/#.*//g' | xargs)

          for file in k8/*.yml
          do
              echo "====${file}===="
              envsubst < "${file}" > "${file}.out" && mv "${file}.out" "${file}"
              cat  "${file}"
              echo "\n"
          done

      - name: Deploy to Kubernetes
        run: |
          kubectl apply --kubeconfig /kubeconfig.yml -f k8
