name: "apply k8"

on:
  push:
    branches:
      - main
      - staging

env:
  IMAGE_TAG: "${{ github.ref_name }}-${{ github.sha }}"

jobs:
  build:
    strategy:
      matrix:
        include:
          - image_name: ${{ github.repository }}-backend
            build_dir: backend
          - image_name: ${{ github.repository }}-frontend
            build_dir: frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{ matrix.image_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=${{ env.IMAGE_TAG }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ matrix.build_dir }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy to katedra2
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          submodules: false

      - name: "Config for production"
        if: github.ref_name == 'main'
        env:
          K8_ENV_FILE: "k8/.env.production"
          KUBECONFIG_PRODUCTION: ${{ secrets.KUBECONFIG_PRODUCTION }}
        run: |
          mv "${K8_ENV_FILE}" k8/.env
          echo "${KUBECONFIG_PRODUCTION}" > _kubeconfig.yml

      - name: "Config for staging"
        if: github.ref_name == 'staging'
        env:
          K8_ENV_FILE: "k8/.env.staging"
          KUBECONFIG_PRODUCTION: ${{ secrets.KUBECONFIG_STAGING }}
        run: |
          mv "${K8_ENV_FILE}" k8/.env
          echo "${KUBECONFIG_PRODUCTION}" > _kubeconfig.yml

      - name: "Envsubst variables in k8/*.yml"
        run: |
          export DOCKER_IMAGE_SHA_TAG="${{ env.IMAGE_TAG }}"
          export $(cat k8/.env | sed 's/#.*//g' | xargs)

          for file in k8/*.yml
          do
              echo "====${file}===="
              envsubst < "${file}" > "${file}.out" && mv "${file}.out" "${file}"
              cat  "${file}"
              echo "\n"
          done

      - name: Deploy to Kubernetes
        run: |
          kubectl apply --kubeconfig _kubeconfig.yml -f k8
